### ISSUE TITLE
[Request][Feature] Add address validation

### ISSUE THREAD

**Issue by longhoangwkm** [chaintope/bitcoinrb#49]
Can we have `valid_address?` like https://github.com/lian/bitcoin-ruby/blob/master/lib/bitcoin.rb#L75.
I'm currently using `Bitcoin::Script.parse_from_addr` as validation method

**Comment by azuchi** [comment]
Thank you for request. I added `Bticoin::Util#valid_address?` with 521edce.

**Comment by longhoangwkm** [comment]
@azuchi Thank you so much, Just small typo here https://github.com/chaintope/bitcoinrb/commit/521edce47c1026bdcf4fcc0327a8803d48baab41#diff-57fe522e75707e90e8147037b69212f7R94 🙇

**Comment by azuchi** [comment]
oh, thanks!
