### ISSUE TITLE
chainparams incorrect for bip49_pubkey_p2wsh_p2sh_version

### ISSUE THREAD

**Issue by iancoleman** [chaintope/bitcoinrb#50]
https://github.com/chaintope/bitcoinrb/blob/f1014406f6b8f9b4edcecedc18df70c80df06f11/lib/bitcoin/chainparams/regtest.yml#L12

According to https://github.com/spesmilo/electrum-docs/blob/master/xpub_version_bytes.rst this is `0x024289ef` not `0x024285ef` (testnet / p2wsh-p2sh / public)

Am I understanding this correctly?

**Comment by azuchi** [comment]
Yes you are right! I fixed it ff81a31.
Thanks!
