### ISSUE TITLE
Disconnected to bitcoin-core node.

### ISSUE THREAD

**Issue by Yamaguchi** [chaintope/bitcoinrb#56]
I tried to connect bitcoin-core nodes("172.18.1.1", "172.18.1.2", "172.18.1.3") as follows.
They were running in regtest mode.

```
c = Bitcoin::Node::Configuration.new(network: :regtest, connect:["172.18.1.1", "172.18.1.2", "172.18.1.3"])
spv = Bitcoin::Node::SPV.new(c)
Thread.start{ spv.run }
```

Then each node accepted the connection from bitcoinrb once but disconnected immediately.

Bitcoin's log is here: (-debug=net is specified)

```
2020-06-28T09:51:59Z Added connection peer=328
2020-06-28T09:51:59Z connection from 172.18.5.1:35578 accepted
2020-06-28T09:51:59Z received: version (103 bytes) peer=328
2020-06-28T09:51:59Z sending version (102 bytes) peer=328
2020-06-28T09:51:59Z send version message: version 70015, blocks=0, us=[::]:0, peer=328
2020-06-28T09:51:59Z sending verack (0 bytes) peer=328
2020-06-28T09:51:59Z receive version message: /bitcoinrb:0.4.0/: version 70013, blocks=1, us=127.0.0.1:18444, peer=328
2020-06-28T09:51:59Z received: verack (0 bytes) peer=328
2020-06-28T09:51:59Z sending sendheaders (0 bytes) peer=328
2020-06-28T09:51:59Z sending ping (8 bytes) peer=328
2020-06-28T09:51:59Z sending feefilter (8 bytes) peer=328
2020-06-28T09:51:59Z received: filterload (625 bytes) peer=328
2020-06-28T09:51:59Z Misbehaving: 172.18.5.1:35578 peer=328 (0 -> 100) BAN THRESHOLD EXCEEDED
2020-06-28T09:51:59Z ProcessMessages(filterload, 625 bytes) FAILED peer=328
2020-06-28T09:51:59Z disconnecting peer=328
```

**Comment by Yamaguchi** [comment]
The message:
```
Misbehaving: 172.18.5.1:35578 peer=328 (0 -> 100) BAN THRESHOLD EXCEEDED
```
means that bitcoinrb sent messages in the wrong way(not corresponding with Bitcoin protocol).

**Comment by azuchi** [comment]
What is the version of Bitcoin Core and what are the service flag settings?

Perhaps it's because we're sending a `filterload` to nodes that don't support bloom.

**Comment by Yamaguchi** [comment]
Core is 0.20.0

```
Bitcoin Core version v0.20.0 (release build)
```

and

I use docker image https://github.com/ruimarinho/docker-bitcoin-core

```
bitcoin1:
    image: ruimarinho/bitcoin-core
    command:
      -printtoconsole
      -regtest=1
      -rpcallowip=172.18.0.0/16
      -rpcuser=user
      -rpcpassword=pass
      -addnode=172.18.1.2:18444
      -debug
      -debug=net
    networks:
      net:
        ipv4_address: 172.18.1.1
```

**Comment by Yamaguchi** [comment]
I'll try to use another image.

**Comment by azuchi** [comment]
Can you confirm your Bitcoin Core's version message which contains services flags.

**Comment by Yamaguchi** [comment]
1033?

```
I, [2020-06-28T09:51:59.972084 #56 #47142266860080]  INFO -- : receive version message. {"version":70015,"services":1033,"timestamp":1593337919,"local_addr":"#<Bitcoin::Message::NetworkAddr:0x00007fb82c17ddd8>","remote_addr":"#<Bitcoin::Message::NetworkAddr:0x00007fb82c17d220>","nonce":9541048738927306158,"user_agent":"/Satoshi:0.20.0/","start_height":0,"relay":true}
```

**Comment by Yamaguchi** [comment]
1033 = NODE_NETWORK_LIMITED(1024) + NODE_WITNESS(8) + NODE_NETWORK(1)
it seems NODE_BLOOM is not contained.

**Comment by azuchi** [comment]
That would be the cause. Core that does not support NODE_BLOOM disconnects when it receives filterload and filteradd by following code.

https://github.com/bitcoin/bitcoin/blob/19e919217e6d62e3640525e4149de1a4ae04e74f/src/net_processing.cpp#L2218-L2229

In case of workaround solution, Core should be started with NODE_BLOOM.

**Comment by Yamaguchi** [comment]
> That would be the cause. Core that does not support NODE_BLOOM disconnects when it receives filterload and filteradd by following code.
> 
> https://github.com/bitcoin/bitcoin/blob/19e919217e6d62e3640525e4149de1a4ae04e74f/src/net_processing.cpp#L2218-L2229

I didn't realize that because this codes has been removed at master branch.

Now, it works with "-peerbloomfilters=1"
I didnt know this flag is defaulted to "off" since 0.19.0
