### ISSUE TITLE
Bitcoin::Secp256k1::Ruby.verify_sig always returns false

### ISSUE THREAD

**Issue by vasaf** [chaintope/bitcoinrb#63]
Currently on `Ruby 3.0.2`, I tried `Ruby 3.0.1`

Also tried switching from creating a signed message with a `segwit bech32` address to a `legacy address` and no matter what the signature returns as false.. Can this issue be verified?

Thanks!

**Comment by azuchi** [comment]
If the correct message, signature and public key are provided, verification will succeed. As in the following test: 

https://github.com/chaintope/bitcoinrb/blob/master/spec/bitcoin/secp256k1/ruby_spec.rb#L63

What data did you fail with?

**Comment by vasaf** [comment]
My bad.. I was trying to verify a message and was using verify_sig instead...

All working with Bitcoin::MessageSign.verify_message
