### ISSUE TITLE
A lot of negations when testing for a positive in Tx#witness?

### ISSUE THREAD

**Issue by bterkuile** [chaintope/bitcoinrb#71]
The method `Bitcoin::Tx#witness?` code seems to mean the following I think:
```ruby
inputs.any?(&:has_witness?)
```

https://github.com/chaintope/bitcoinrb/blob/850add827b2c80c3912bb92f1321c324728b7d50/lib/bitcoin/tx.rb#L114

**Comment by azuchi** [comment]
it's correct, can you create pull requrest?
